FROM docker.io/calendso/calendso@sha256:ace3bb1219fb7306585ab9f4d94d41af7ee064c343db0498173436bbe857bd49

COPY brand/voxpilot-wordmark-ink.svg /calcom/apps/web/public/calcom-logo-white-word.svg
COPY brand/voxpilot-wordmark-ink.svg /calcom/apps/web/public/cal-logo-word-black.svg
COPY brand/voxpilot-mark-full-color.svg /calcom/apps/web/public/cal-com-icon-white.svg

LABEL org.opencontainers.image.title="VoxPilot Scheduling" \
      org.opencontainers.image.description="VoxPilot-owned scheduling product layer built on Cal.diy" \
      org.opencontainers.image.source="https://github.com/ekohamllc/voxpilot-scheduling" \
      org.opencontainers.image.licenses="MIT" \
      io.voxpilot.product="VoxPilot Scheduling" \
      io.voxpilot.release="2026.08.12-source.1" \
      io.voxpilot.base-digest="sha256:ace3bb1219fb7306585ab9f4d94d41af7ee064c343db0498173436bbe857bd49"
